import React, { useEffect, useMemo, useState } from "react";
import { createRoot } from "react-dom/client";
import { api, unauthorizedEvent, textApi, type Envelope } from "./api";
import type { AuditEvent, Incident, Indicator, NetworkRecord, Provider } from "./types";
import "./styles.css";

type View = "overview" | "incidents" | "threats" | "network" | "trust" | "administration" | "audit";
const views: Array<[View, string, string]> = [
  ["overview", "Overview", "⌂"], ["incidents", "Incident Center", "◎"], ["threats", "Threat Intelligence", "◈"],
  ["network", "Network Intelligence", "⌁"], ["trust", "Trust Management", "✓"], ["administration", "Administration", "⚙"], ["audit", "Audit", "≡"]
];

function useApi<T>(path: string, token: string | null, fallback: T) {
  const [data, setData] = useState(fallback);
  const [loading, setLoading] = useState(true);
  const [error, setError] = useState<string | null>(null);
  const [pagination, setPagination] = useState<Envelope<T>["pagination"]>(null);
  const [revision, setRevision] = useState(0);
  useEffect(() => {
    if (!token && path !== "/health" && path !== "/ready") { setLoading(false); return; }
    let cancelled = false;
    setLoading(true); setError(null);
    api<Envelope<T>>(path, token ?? undefined).then((response) => { if (!cancelled) { setData(response.data); setPagination(response.pagination ?? null); } }).catch((reason: unknown) => { if (!cancelled) setError(reason instanceof Error ? reason.message : "API request failed"); }).finally(() => { if (!cancelled) setLoading(false); });
    return () => { cancelled = true; };
  }, [path, token, revision]);
  return { data, loading, error, pagination, reload: () => setRevision((value) => value + 1) };
}

function useTextApi(path: string, token: string | null) {
  const [data, setData] = useState(""); const [error, setError] = useState<string | null>(null);
  useEffect(() => { if (!token) return; let cancelled = false; textApi(path, token).then((value) => { if (!cancelled) setData(value); }).catch((reason: unknown) => { if (!cancelled) setError(reason instanceof Error ? reason.message : "API request failed"); }); return () => { cancelled = true; }; }, [path, token]);
  return { data, error };
}

function Card({ title, value, hint, tone = "default" }: { title: string; value: React.ReactNode; hint?: string; tone?: string }) {
  return <section className={"card metric " + tone}><span className="eyebrow">{title}</span><strong>{value}</strong>{hint && <small>{hint}</small>}</section>;
}
function Table({ children }: { children: React.ReactNode }) { return <div className="table-wrap"><table>{children}</table></div>; }
function Empty({ text = "No records returned by the API." }: { text?: string }) { return <div className="empty">{text}</div>; }
function Loading() { return <div className="empty">Loading API data…</div>; }
function PageTitle({ eyebrow, title, subtitle }: { eyebrow: string; title: string; subtitle: string }) { return <div className="page-heading"><div><p className="eyebrow">{eyebrow}</p><h2>{title}</h2><p className="muted">{subtitle}</p></div></div>; }
function Badge({ value }: { value: string }) { return <span className={"badge " + value.toLowerCase().replaceAll(" ", "-")}>{value}</span>; }
function Meter({ value }: { value: number }) { return <span className="meter"><i style={{ width: Math.max(0, Math.min(100, value)) + "%" }} /><em>{value}</em></span>; }
function formatDate(value: string) { if (!value) return "—"; const date = new Date(value); return Number.isNaN(date.valueOf()) ? value : date.toLocaleString(); }
function ErrorNotice({ error }: { error: string | null }) { return error ? <div className="form-error api-error">{error}</div> : null; }
function Pager({ page, pagination, onPage }: { page: number; pagination: Envelope<unknown>["pagination"]; onPage: (page: number) => void }) {
  if (!pagination || (pagination.total <= pagination.page_size && page === 1)) return null;
  return <div className="pager"><button disabled={page <= 1} onClick={() => onPage(page - 1)}>Previous</button><span>Page {pagination.page} · {pagination.total} records</span><button disabled={!pagination.has_next} onClick={() => onPage(page + 1)}>Next</button></div>;
}
function SearchControls({ search, setSearch, children }: { search: string; setSearch: (value: string) => void; children?: React.ReactNode }) {
  return <div className="toolbar"><label className="search-label">Search<input value={search} onChange={(event) => setSearch(event.target.value)} placeholder="Filter current results" /></label>{children}</div>;
}

function Login({ onLogin }: { onLogin: (token: string) => void }) {
  const [username, setUsername] = useState("admin"); const [password, setPassword] = useState(""); const [error, setError] = useState("");
  async function submit(event: React.FormEvent) {
    event.preventDefault(); setError("");
    try {
      const response = await api<Envelope<{ token: string }>>("/admin/auth/login", undefined, { method: "POST", body: JSON.stringify({ username, password }) });
      sessionStorage.setItem("clawforge_token", response.data.token); onLogin(response.data.token);
    } catch (reason) { setError(reason instanceof Error ? reason.message : "Login failed"); }
  }
  return <main className="login-shell"><div className="login-card"><div className="brand-mark">C</div><p className="eyebrow">SECURITY INTELLIGENCE</p><h1>Clawforge Console</h1><p className="muted">Sign in through the Clawforge API to view operational data.</p><form onSubmit={submit}><label>Username<input value={username} onChange={(e) => setUsername(e.target.value)} autoComplete="username" /></label><label>Password<input type="password" value={password} onChange={(e) => setPassword(e.target.value)} autoComplete="current-password" /></label>{error && <div className="form-error">{error}</div>}<button className="primary" type="submit">Sign in</button></form></div></main>;
}

function Overview({ token }: { token: string }) {
  const incidents = useApi<Incident[]>("/incidents?status=Open&page_size=5", token, []);
  const providers = useApi<Provider[]>("/intelligence/providers", token, []);
  const events = useApi<AuditEvent[]>("/audit/events?page_size=5", token, []);
  const health = useApi<Record<string, unknown>>("/health", null, {}); const ready = useApi<Record<string, unknown>>("/ready", null, {});
  const metrics = useTextApi("/metrics", token);
  const activeProviders = providers.data.filter((provider) => provider.enabled).length;
  const highestRisk = incidents.data.reduce((highest, item) => Math.max(highest, item.risk_score), 0);
  return <><div className="page-heading"><div><p className="eyebrow">OPERATIONS</p><h2>Overview</h2><p className="muted">A read-only view of current Clawforge intelligence.</p></div><span className="live-dot">Live API</span></div><ErrorNotice error={incidents.error || providers.error || events.error} /><div className="metric-grid"><Card title="Open incidents" value={incidents.data.length} tone={incidents.data.length ? "alert" : "good"} /><Card title="Highest open risk" value={highestRisk} hint="Presented from API risk scores" tone={highestRisk >= 70 ? "alert" : "default"} /><Card title="Providers enabled" value={activeProviders + "/" + providers.data.length} /><Card title="System status" value={health.error ? "Unavailable" : "Healthy"} hint={ready.error ? "Readiness unavailable" : "PostgreSQL ready"} tone={health.error || ready.error ? "alert" : "good"} /></div><div className="two-col"><section className="card"><div className="section-title"><h3>Open incidents</h3><span>Latest from API</span></div>{incidents.loading ? <Loading /> : incidents.data.length ? <Table><thead><tr><th>Severity</th><th>Summary</th><th>Risk</th><th>Updated</th></tr></thead><tbody>{incidents.data.map((item) => <tr key={item.id}><td><Badge value={item.severity} /></td><td>{item.summary}</td><td>{item.risk_score}</td><td>{formatDate(item.updated_at)}</td></tr>)}</tbody></Table> : <Empty text="No open incidents." />}</section><section className="card"><div className="section-title"><h3>Provider status</h3><span>{providers.loading ? "Loading…" : providers.data.length + " registered"}</span></div><Table><thead><tr><th>Provider</th><th>State</th><th>Indicators</th><th>Last sync</th></tr></thead><tbody>{providers.data.slice(0, 6).map((item) => <tr key={item.id}><td>{item.name}</td><td><Badge value={item.status ?? (item.enabled ? "enabled" : "disabled")} /></td><td>{item.indicator_count ?? "—"}</td><td>{formatDate(item.last_success_at ?? "")}</td></tr>)}</tbody></Table></section></div><div className="two-col"><section className="card"><div className="section-title"><h3>Worker status</h3><span>Runtime metrics</span></div><p className="muted panel-copy">{metrics.error ? "Unavailable: " + metrics.error : metrics.data ? "Metrics available from API" : "Loading worker metrics…"}</p></section><section className="card"><div className="section-title"><h3>Latest events</h3><span>Audit API</span></div>{events.data.length ? <Table><thead><tr><th>Time</th><th>Actor</th><th>Severity</th><th>Reason</th></tr></thead><tbody>{events.data.map((item) => <tr key={item.id}><td>{formatDate(item.recorded_at)}</td><td>{item.actor}</td><td><Badge value={item.severity} /></td><td>{item.reason}</td></tr>)}</tbody></Table> : <Empty text="No recent events." />}</section></div></>;
}
function Incidents({ token }: { token: string }) {
  const [page, setPage] = useState(1); const [status, setStatus] = useState(""); const [severity, setSeverity] = useState(""); const [search, setSearch] = useState(""); const [selected, setSelected] = useState<Incident | null>(null); const [statusError, setStatusError] = useState(""); const [statusBusy, setStatusBusy] = useState(false);
  const result = useApi<Incident[]>("/incidents?page=" + page + "&page_size=25" + (status ? "&status=" + encodeURIComponent(status) : "") + (severity ? "&severity=" + encodeURIComponent(severity) : ""), token, []);
  const events = useApi<Array<Record<string, unknown>>>(selected ? "/incidents/" + selected.id + "/events" : "/incidents/invalid/events", token, []); const analysis = useApi<Record<string, unknown>>(selected ? "/incidents/" + selected.id + "/analysis" : "/incidents/invalid/analysis", token, {});
  const displayed = result.data.filter((item) => !search || (item.summary + " " + item.id).toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.updated_at.localeCompare(a.updated_at));
  async function changeStatus(nextStatus: string) { if (!selected) return; setStatusBusy(true); setStatusError(""); try { await api<Envelope<unknown>>("/incidents/" + selected.id + "/status", token, { method: "POST", body: JSON.stringify({ status: nextStatus }) }); setSelected({ ...selected, status: nextStatus, updated_at: new Date().toISOString() }); result.reload(); } catch (reason) { setStatusError(reason instanceof Error ? reason.message : "Status update failed"); } finally { setStatusBusy(false); } }
  const grouped = events.data.reduce<Record<string, Array<Record<string, unknown>>>>((groups, event) => { const key = String(event.event_type ?? event.source ?? "event"); (groups[key] ??= []).push(event); return groups; }, {});
  return <><PageTitle eyebrow="CORRELATION" title="Incident Center" subtitle="Correlated events and structured analysis from the API." /><SearchControls search={search} setSearch={(value) => { setSearch(value); setPage(1); }}><label>State<select value={status} onChange={(event) => { setStatus(event.target.value); setPage(1); }}><option value="">All states</option><option>Open</option><option>Investigating</option><option>Resolved</option><option>Ignored</option></select></label><label>Severity<select value={severity} onChange={(event) => { setSeverity(event.target.value); setPage(1); }}><option value="">All severities</option><option>critical</option><option>high</option><option>medium</option><option>low</option></select></label></SearchControls><ErrorNotice error={result.error || statusError} />{result.loading ? <Loading /> : <div className="incident-layout"><section className="card incident-list"><div className="section-title"><h3>Incidents</h3><span>{result.pagination?.total ?? result.data.length} total</span></div>{displayed.length ? displayed.map((item) => <button className={"incident-row " + (selected?.id === item.id ? "selected" : "")} key={item.id} onClick={() => setSelected(item)}><Badge value={item.severity} /><span><b>{item.summary}</b><small>{item.status} · {formatDate(item.updated_at)}</small></span><strong>{item.risk_score}</strong></button>) : <Empty />}</section><section className="card detail-panel">{selected ? <><div className="section-title"><div><p className="eyebrow">{selected.id}</p><h3>{selected.summary}</h3></div><div className="status-actions"><Badge value={selected.status} /><select aria-label="Change incident status" value={selected.status} disabled={statusBusy} onChange={(event) => void changeStatus(event.target.value)}><option>Open</option><option>Investigating</option><option>Resolved</option><option>Ignored</option></select></div></div><h4>Correlated events</h4>{events.loading ? <Loading /> : Object.keys(grouped).length ? Object.entries(grouped).map(([group, groupEvents]) => <div className="event-group" key={group}><span className="eyebrow">{group}</span>{groupEvents.map((event, index) => <div className="timeline-item" key={String(event.event_id ?? index)}><span className="timeline-dot" /><div><b>{String(event.event_type ?? event.action ?? "event")}</b><small>{String(event.source ?? "API")} · {formatDate(String(event.timestamp ?? event.recorded_at ?? ""))}</small><p>{String(event.reason ?? "")}</p></div></div>)}</div>) : <Empty text="No correlated events." />}<h4>Analysis</h4>{analysis.loading ? <Loading /> : <pre className="analysis">{JSON.stringify(analysis.data, null, 2)}</pre>}</> : <Empty text="Select an incident to inspect its timeline." />}</section></div>}<Pager page={page} pagination={result.pagination} onPage={setPage} /></>;
}
function Threats({ token }: { token: string }) {
  const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [source, setSource] = useState(""); const [severity, setSeverity] = useState(""); const [sort, setSort] = useState("last_seen");
  const result = useApi<Indicator[]>("/intelligence/indicators?page=" + page + "&page_size=25" + (source ? "&source=" + encodeURIComponent(source) : "") + (severity ? "&severity=" + encodeURIComponent(severity) : ""), token, []);
  const displayed = result.data.filter((item) => !search || (item.value + " " + item.indicator_type).toLowerCase().includes(search.toLowerCase())).sort((a, b) => String(b[sort as keyof Indicator] ?? "").localeCompare(String(a[sort as keyof Indicator] ?? "")));
  return <><PageTitle eyebrow="FEEDS" title="Threat Intelligence" subtitle="Normalized indicators, source context, age, and confidence." /><SearchControls search={search} setSearch={(value) => { setSearch(value); setPage(1); }}><label>Source<input value={source} onChange={(event) => { setSource(event.target.value); setPage(1); }} placeholder="ThreatFox" /></label><label>Severity<select value={severity} onChange={(event) => { setSeverity(event.target.value); setPage(1); }}><option value="">All</option><option>critical</option><option>high</option><option>medium</option><option>low</option></select></label><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="last_seen">Last seen</option><option value="confidence">Confidence</option><option value="risk_score">Risk</option></select></label></SearchControls><ErrorNotice error={result.error} />{result.loading ? <Loading /> : <section className="card"><Table><thead><tr><th>Indicator</th><th>Type</th><th>Source</th><th>Confidence</th><th>Risk</th><th>Last seen</th></tr></thead><tbody>{displayed.map((item) => <tr key={item.id}><td className="mono">{item.value}</td><td>{item.indicator_type}</td><td>{item.source}</td><td><Meter value={item.confidence} /></td><td>{item.risk_score ?? "—"}</td><td>{formatDate(item.last_seen)}</td></tr>)}</tbody></Table>{!displayed.length && <Empty />}</section>}<Pager page={page} pagination={result.pagination} onPage={setPage} /></>;
}
function Network({ token }: { token: string }) {
  const asn = useApi<NetworkRecord[]>("/network/asn?page_size=100", token, []); const bgp = useApi<NetworkRecord[]>("/network/bgp?page_size=100", token, []); const rpki = useApi<NetworkRecord[]>("/network/rpki", token, []);
  return <><PageTitle eyebrow="NETWORK" title="Network Intelligence" subtitle="ASN context, routing changes, and RPKI validation." /><div className="two-col"><section className="card"><div className="section-title"><h3>ASN records</h3><span>{asn.data.length}</span></div><Table><thead><tr><th>ASN</th><th>Organisation</th><th>Country</th><th>Reputation</th></tr></thead><tbody>{asn.data.map((item, i) => <tr key={String(item.asn ?? i)}><td className="mono">{String(item.asn ?? "—")}</td><td>{String(item.organisation ?? item.name ?? "—")}</td><td>{String(item.country ?? "—")}</td><td>{String(item.reputation ?? "—")}</td></tr>)}</tbody></Table></section><section className="card"><div className="section-title"><h3>RPKI status</h3><span>{rpki.data.length}</span></div><Table><thead><tr><th>Prefix</th><th>ASN</th><th>Status</th><th>Source</th></tr></thead><tbody>{rpki.data.map((item, i) => <tr key={String(item.prefix ?? i)}><td className="mono">{String(item.prefix ?? "—")}</td><td>{String(item.asn ?? "—")}</td><td><Badge value={String(item.status ?? "unknown")} /></td><td>{String(item.source ?? "—")}</td></tr>)}</tbody></Table></section></div><section className="card"><div className="section-title"><h3>BGP events</h3><span>{bgp.data.length}</span></div><Table><thead><tr><th>Prefix</th><th>Origin</th><th>Change</th><th>RPKI</th><th>Timestamp</th></tr></thead><tbody>{bgp.data.map((item, i) => <tr key={String(item.prefix ?? i)}><td className="mono">{String(item.prefix ?? "—")}</td><td>{String(item.origin_asn ?? "—")}</td><td><Badge value={String(item.status ?? "—")} /></td><td><Badge value={String(item.rpki_status ?? "—")} /></td><td>{formatDate(String(item.timestamp ?? ""))}</td></tr>)}</tbody></Table></section></>;
}

function Trust({ token }: { token: string }) { const result = useApi<NetworkRecord[]>("/network/trust", token, []); return <><PageTitle eyebrow="TRUST REGISTRY" title="Trust Management" subtitle="Explicitly registered infrastructure and its current verification state." /><section className="card"><Table><thead><tr><th>Name</th><th>Type</th><th>Identifier</th><th>Status</th><th>Trust</th></tr></thead><tbody>{result.data.map((item, i) => <tr key={String(item.id ?? i)}><td>{String(item.name ?? "—")}</td><td>{String(item.type ?? "—")}</td><td className="mono">{String(item.identifier ?? "—")}</td><td><Badge value={String(item.status ?? "—")} /></td><td>{String(item.trust_score ?? "—")}</td></tr>)}</tbody></Table>{!result.data.length && !result.loading && <Empty />}</section></>; }

function Administration({ token }: { token: string }) { const [search, setSearch] = useState(""); const [sort, setSort] = useState("name"); const providers = useApi<Provider[]>("/admin/providers", token, []); const config = useApi<Array<Record<string, unknown>>>("/admin/config", token, []); const shown = providers.data.filter((item) => !search || (item.name + " " + item.source).toLowerCase().includes(search.toLowerCase())).sort((a, b) => String(a[sort as keyof Provider] ?? "").localeCompare(String(b[sort as keyof Provider] ?? ""))); return <><PageTitle eyebrow="CONTROL PLANE" title="Administration" subtitle="Configuration remains enforced by the API and role permissions." /><SearchControls search={search} setSearch={setSearch}><label>Sort<select value={sort} onChange={(event) => setSort(event.target.value)}><option value="name">Name</option><option value="status">Status</option><option value="indicator_count">Indicators</option></select></label></SearchControls><ErrorNotice error={providers.error || config.error} /><div className="two-col"><section className="card"><div className="section-title"><h3>Providers</h3><span>{shown.length} shown · API managed</span></div><Table><thead><tr><th>Name</th><th>Enabled</th><th>State</th><th>Last error</th></tr></thead><tbody>{shown.map((item) => <tr key={item.id}><td>{item.name}</td><td><Badge value={item.enabled ? "enabled" : "disabled"} /></td><td>{item.status ?? "—"}</td><td>{item.last_error ?? "—"}</td></tr>)}</tbody></Table></section><section className="card"><div className="section-title"><h3>Configuration</h3><span>Secrets excluded</span></div><pre className="analysis">{JSON.stringify(config.data, null, 2)}</pre></section></div></>; }
function Audit({ token }: { token: string }) { const [page, setPage] = useState(1); const [search, setSearch] = useState(""); const [source, setSource] = useState(""); const [severity, setSeverity] = useState(""); const result = useApi<AuditEvent[]>("/audit/events?page=" + page + "&page_size=25" + (source ? "&source=" + encodeURIComponent(source) : "") + (severity ? "&severity=" + encodeURIComponent(severity) : ""), token, []); const shown = result.data.filter((item) => !search || (item.actor + " " + item.action + " " + item.resource + " " + item.reason).toLowerCase().includes(search.toLowerCase())).sort((a, b) => b.recorded_at.localeCompare(a.recorded_at)); return <><PageTitle eyebrow="TRACEABILITY" title="Audit" subtitle="Administrative and intelligence events recorded by the backend." /><SearchControls search={search} setSearch={(value) => { setSearch(value); setPage(1); }}><label>Source<input value={source} onChange={(event) => { setSource(event.target.value); setPage(1); }} placeholder="Source" /></label><label>Severity<select value={severity} onChange={(event) => { setSeverity(event.target.value); setPage(1); }}><option value="">All</option><option>critical</option><option>high</option><option>medium</option><option>low</option></select></label></SearchControls><ErrorNotice error={result.error} /><section className="card"><Table><thead><tr><th>Time</th><th>Actor</th><th>Action</th><th>Resource</th><th>Severity</th><th>Reason</th></tr></thead><tbody>{shown.map((item) => <tr key={item.id}><td>{formatDate(item.recorded_at)}</td><td>{item.actor}</td><td>{item.action}</td><td className="mono">{item.resource}</td><td><Badge value={item.severity} /></td><td>{item.reason}</td></tr>)}</tbody></Table>{!shown.length && !result.loading && <Empty />}</section><Pager page={page} pagination={result.pagination} onPage={setPage} /></>; }
function App() {
  const [token, setToken] = useState(() => sessionStorage.getItem("clawforge_token")); const [view, setView] = useState<View>("overview");
  useEffect(() => { const logout = () => { sessionStorage.removeItem("clawforge_token"); setToken(null); }; window.addEventListener(unauthorizedEvent, logout); return () => window.removeEventListener(unauthorizedEvent, logout); }, []);
  const content = useMemo(() => { if (!token) return null; switch (view) { case "overview": return <Overview token={token} />; case "incidents": return <Incidents token={token} />; case "threats": return <Threats token={token} />; case "network": return <Network token={token} />; case "trust": return <Trust token={token} />; case "administration": return <Administration token={token} />; case "audit": return <Audit token={token} />; } }, [token, view]);
  if (!token) return <Login onLogin={setToken} />;
  return <div className="app-shell"><aside className="sidebar"><div className="brand"><div className="brand-mark">C</div><div><b>CLAWFORGE</b><small>INTELLIGENCE CONSOLE</small></div></div><nav>{views.map(([id, label, icon]) => <button key={id} className={view === id ? "active" : ""} onClick={() => setView(id)}><span>{icon}</span>{label}</button>)}</nav><div className="sidebar-footer"><span className="status-led" />API connected<button className="logout" onClick={() => { sessionStorage.removeItem("clawforge_token"); setToken(null); }}>Sign out</button></div></aside><main className="content">{content}</main></div>;
}

createRoot(document.getElementById("root")!).render(<App />);
